---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  labels:
    wego.weave.works/app-identifier: wego-73e9111d78605dd17a06f2fcdca6e8e2
  name: podinfo-deploy
  namespace: wego-system
spec:
  branch: main
  deployment_type: kustomize
  path: ./
  source_type: git
  url: ssh://git@github.com/deobieta/podinfo-deploy.git
